# Numpy
Numerical Python (NumPy) is a popular Python library used for numerical computations and handling arrays or matrices.
It provides support for multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

#### Why do we use NumPy?

* `Efficient Array Operations`: NumPy allows for fast operations on arrays/matrix computations, making it essential for scientific and numerical calculations.
* `Data Representation`: It provides a convenient and efficient way of representing and manipulating numerical data.
* `Integration with Other Libraries`: It integrates well with other Python libraries and tools used in data analysis, machine learning, and scientific computing.

#### Advantages of NumPy:

* `Performance`: It's highly optimized and written in C, making operations significantly faster than standard Python lists for numerical computations.
* `Broadcasting`: Allows operations on arrays of different shapes, which makes code concise and easier to read.
* `Array-Oriented Computing`: Provides a wide range of mathematical functions for fast operations on entire arrays without the need for writing loops.
* `Memory Efficiency`: NumPy arrays use less memory compared to Python lists for storing data.
* `Broad Usage`: Widely used in fields like data science, machine learning, scientific research, and engineering due to its speed and functionality.


#### Scalar Values
Doesnt have any dimesion

In [1]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

print(a) # prints
print(a.shape) # prints the shape of the object () = 0 -Denormalized
print(a.dtype) # prints the dtype of the object
print(a.ndim) # prints the number of dimensions - Scalar values have 0 dimension
print(a.size) # prints the size of the object
print(a.itemsize) # prints the itemsize of the object


1000
()
int32
0
1
4


#### Vector Type

In [8]:

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

a.size?

' object [1 2 3 4]'

'objec shape (4,)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in Array : 4'

'4'

Type:        int
String form: 4
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

#### Matrix

In [9]:
data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'objec shape (3, 4)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in Array : 12'

'4'

### Numpy with NDArray typing support

In [2]:
%%time 
from nptyping import NDArray, Shape, UInt32
from typing import Any

data : NDArray[Shape["10"],Any] = np.arange(1,20);

d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
#d1 + 5 #will give error because doesnt work on list

print(data);
print(data + 5)
print(data ** 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
CPU times: total: 0 ns
Wall time: 65.3 ms


In [11]:
print("List Method\n")
data1 : list[int] = list(range(1,21))
print(data1)
print(data1[5:11])
#data1[5:11] = 1000 #list doesnt allow this operation
print(data1)

print("\nNumpy Mehtod \n")
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)


List Method

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Numpy Mehtod 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


In [3]:
from typing import Any
from nptyping import NDArray, Shape, Bool


state_bank : NDArray[Shape["10"], Any] = np.array([1, 7, 8, 10])
select : NDArray[Shape["10"], Bool] = np.array([True, False, False, True])

ubl_bank : NDArray[Shape["100"], Any] = np.random.randint(1, 100, 20);

display(state_bank)
display(state_bank[select])

display(ubl_bank)
display(ubl_bank[ubl_bank % 2 == 0])

array([ 1,  7,  8, 10])

array([ 1, 10])

array([54, 45, 65, 95, 91, 55, 50, 41,  4, 63, 61, 38,  5, 34, 78, 56, 53,
       85, 57, 73])

array([54, 50,  4, 38, 34, 78, 56])

In [21]:
x : NDArray[Shape["5"], Any] = np.array([1, 3, 4, 5, 7])
y : NDArray[Shape["5"], Any] = np.array([6, 3, 2, 5, 100])

display(x)
np.where(x > y, x, y)


array([1, 3, 4, 5, 7])

array([  6,   3,   4,   5, 100])

In [23]:
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                [4, 5, 6]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                [4, 5]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                ["B"]])


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


#### Create any dimension array

In [15]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(f"1D Array: {a}")

a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3)
print(f"\n2D Array \n{a}")

a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(f"\n3D Array \n{a}")

1D Array: [1 2 3 4]

2D Array 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3D Array 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [16]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Pandas
Pandas is a popular open-source data manipulation and analysis library for Python. It provides powerful and easy-to-use data structures, such as Series (1-dimensional) and DataFrame (2-dimensional), which are designed to make working with structured data more intuitive

#### <b>Key Components:</b>
`DataFrame`: <br/>
A 2-dimensional tabular data structure resembling a spreadsheet or SQL table. It consists of rows and columns, each of which can contain different data types (integers, strings, floats, etc.).
<br/>
`Series:`<br/>
A one-dimensional array-like object that can hold data of any type. A DataFrame consists of multiple Series objects.

#### <b>Key Components:</b>
`Data Cleaning and Preparation`:<br/>
Pandas is extensively used for data cleaning tasks, such as handling missing data (NaN), removing duplicates, and transforming data into a more usable format.

`Data Manipulation`: <br/>
It allows for efficient manipulation of data, including selecting, filtering, sorting, aggregating, and merging data sets.

`Data Analysis`: <br/>
Pandas provides functionalities to perform various statistical and mathematical operations on datasets. Users can calculate descriptive statistics, apply functions to data, and generate summary reports easily.

`Time Series Analysis`: <br/>
Pandas offers powerful tools for working with time series data, enabling date and time functionalities, such as date range generation, shifting, lagging, and windowing operations.

`Data Visualization`: <br/>
While Pandas itself doesn't handle visualization, it integrates well with other libraries like Matplotlib and Seaborn to create visual representations of data directly from DataFrames.



In [7]:
%pip install pandas
%pip install pandera

Note: you may need to restart the kernel to use updated packages.
     ---------------------------------------- 0.0/158.6 kB ? eta -:--:--
     -- ------------------------------------- 10.2/158.6 kB ? eta -:--:--
     -------------- ---------------------- 61.4/158.6 kB 656.4 kB/s eta 0:00:01
     ---------------------------------- --- 143.4/158.6 kB 1.1 MB/s eta 0:00:01
     ------------------------------------ 158.6/158.6 kB 862.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/203.4 kB ? eta -:--:--
   ------------ --------------------------- 61.4/203.4 kB 3.2 MB/s eta 0:00:01
   ------------ --------------------------- 61.4/203.4 kB 3.2 MB/s eta 0:00:01
   ------------ --------------------------- 61.4/203.4 kB 3.2 MB/s eta 0:00:01
   ------------ --------------------------- 61.4/203.4 kB 3.2 MB/s eta 0:00:01
   ------------ --------------------------- 61.4/203.4 kB 3.2 MB/s eta 0:00:01
   ------------------------------------ - 194.6/203.4 kB 784.3 kB/s eta 0:00:01
 

In [1]:
import pandas as pd
import pandera as pa

In [4]:
s1 : pd.Series[int] = pd.Series([1,2,3,4,5])
s1

TypeError: type 'Series' is not subscriptable

In [ ]:
#Set cannot be used for creating series
s1 : pd.Series = pd.Series({1,2,3,4,5})
s1

In [7]:
#Tuple can be used for creating series
s1 : pd.Series = pd.Series((1,2,3,4,5))
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#List can be used for creating series
s1 : pd.Series = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
#Dictionary can be used for creating series
s1 : pd.Series = pd.Series({"A":10,
                            "B":20,
                            "C":30,
                            "D":40})
s1

A    10
B    20
C    30
D    40
dtype: int64

In [10]:
values : list[int] = [1, 2, 3, 4, 5];
index1 : list[str] = ['a', 'b', 'c', 'd', 'e'];

s1 : pd.Series = pd.Series(values, index=index1)
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [14]:
values : list[int] = [1, 2, 3, 4, 5];
index1 : list[list[str]] = [['a1', 'a1', 'b1', 'b1', 'c1'],
                            ['a', 'b', 'c', 'd', 'e']]; #grouping data

s1 : pd.Series = pd.Series(values, index=index1, name="Student_Data")
s1

a1  a    1
    b    2
b1  c    3
    d    4
c1  e    5
Name: Student_Data, dtype: int64

In [16]:
from nptyping import DataFrame, Structure as S
import pandas as pd
import pandera as pa

# data to validate
df = pd.DataFrame({
    "column1": [1, 4, 0, 10, 9],
    "column2": [-1.3, -1.4, -2.9, -10.1, -20.4],
    "column3": ["value_1", "value_2", "value_3", "value_2", "value_1"],
})

# define schema
schema = pa.DataFrameSchema({
    "column1": pa.Column(int, checks=pa.Check.le(10)),
    "column2": pa.Column(float, checks=pa.Check.lt(-1.2)),
    "column3": pa.Column(str, checks=[
        pa.Check.str_startswith("value_"),
        # define custom checks as functions that take a series as input and
        # outputs a boolean or boolean Series
        pa.Check(lambda s: s.str.split("_", expand=True).shape[1] == 2)
    ]),
})

validated_df = schema(df)
print(validated_df)

   column1  column2  column3
0        1     -1.3  value_1
1        4     -1.4  value_2
2        0     -2.9  value_3
3       10    -10.1  value_2
4        9    -20.4  value_1


##### DataFrame

In [22]:
s1 : pd.Series = pd.Series([1,2,3,4,5], name="student id")
s2 : pd.Series = pd.Series([10,20,30,40,50], name="score")
s3 : pd.Series = pd.Series(["Hamza", "Ali", "Junaid", "Rashid", "Konain"], name="Student Name")

df1 : pd.DataFrame = pd.DataFrame({"student id" : s1, "score" : s2, "student name" : s3})
df1 

student id  score student name
0           1     10        Hamza
1           2     20          Ali
2           3     30       Junaid
3           4     40       Rashid
4           5     50       Konain

In [23]:
df2 : pd.DataFrame = pd.concat([s1, s2, s3], axis=1)
df2

student id  score Student Name
0           1     10        Hamza
1           2     20          Ali
2           3     30       Junaid
3           4     40       Rashid
4           5     50       Konain

In [29]:
from nptyping import NDArray, Shape, UInt64
from typing import Any

data : NDArray[Shape["10, 10"], Any] = np.arange(10*10).reshape(10, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
data : NDArray[Shape["10, 10"], Any] = np.arange(10*10).reshape(10, 10);
df : pd.DataFrame = pd.DataFrame(data);
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [37]:
dfl : list[pd.DataFrame] = pd.read_html("https://www.w3schools.com/python/python_operators.asp")
dfl[0]

Operator            Name Example    Try it
0        +        Addition   x + y  Try it »
1        -     Subtraction   x - y  Try it »
2        *  Multiplication   x * y  Try it »
3        /        Division   x / y  Try it »
4        %         Modulus   x % y  Try it »
5       **  Exponentiation  x ** y  Try it »
6       //  Floor division  x // y  Try it »

In [42]:

s1 : pd.Series = pd.Series([1,2,3,4,5])
display(s1)
print("Applying sliding")
display(s1[3])# index
display(s1[2:4])
display(s1.iloc[1:4]) #index location (numbers) same as numpy slicing index


0    1
1    2
2    3
3    4
4    5
dtype: int64

Applying sliding


4

2    3
3    4
dtype: int64

1    2
2    3
3    4
dtype: int64

In [46]:
x : str = """
20:03:10 From Dr. Ghulam Shabbir to Everyone:
	AoA Honorable Sir Qasim Sb. Stay blessed always iA.
20:03:41 From M Qasim to Everyone:
	sir aj payare lag rahy hy
20:04:02 From Dr. Ghulam Shabbir to Everyone:
	Fantastic
20:04:06 From jhon wick to Qasim(CGAIO)(Direct Message):
	sir aj zia khan sir ne nahi ana
20:04:37 From jhon wick to Everyone:
	Reacted to "sir aj payare lag ra..." with 😂
20:04:44 From M Qasim to Everyone:
	Reacted to "sir aj payare lag ra..." with 😂
20:04:54 From M Qasim to Everyone:
	Removed a 😂 reaction from "sir aj payare lag ra..."
20:04:56 From M Qasim to Everyone:
	Reacted to "sir aj payare lag ra..." with 😂
20:04:57 From M Qasim to Everyone:
	Removed a 😂 reaction from "sir aj payare lag ra..."
20:06:04 From Abdullah to Everyone:
	sir ap kal ki class me ni ayen gy kia??
20:06:04 From M Qasim to Everyone:
	Sir Faisalabad b a rahy hy kya ap?
20:06:49 From Yasir to Everyone:
	Sir generative ai ki class online b hogi na?????
20:07:17 From Sheikh Hamza to Everyone:
	Sir data analytics ke liye maths statistics and probability ani chaye??
20:07:24 From Yasir to Everyone:
	Replying to "Sir generative ai ki..."
	
	@Ikhlas Bhojani PLease ask from sir?
20:07:57 From Ikhlas Bhojani to Everyone:
	Replying to "Sir generative ai ki..."
	
	ok wait
20:08:52 From Dr. Ghulam Shabbir to Everyone:
	Sir Qasim Sb. You were frequently discussed and were given honored and salute in our today's class at Islamabad. Dr. Ghulam Shabbir
20:09:12 From STONE to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:15 From Hatif Humayun to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:19 From Dr. Ghulam Shabbir to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:27 From STONE to Everyone:
	Removed a 👍 reaction from "Sir Qasim Sb. You we..."
20:09:33 From STONE to Everyone:
	Reacted to "Sir Qasim Sb. You we..." with 👍
20:09:34 From STONE to Everyone:
	Removed a 👍 reaction from "Sir Qasim Sb. You we..."
20:12:02 From Amanat Wattoo to Everyone:
	Pd kia convention h
20:12:20 From Amanat Wattoo to Everyone:
	Ya koi or be naam de skte hn
20:12:33 From farhan to Everyone:
	Convention hey
20:12:50 From KifayatUllah to Everyone:
	screen is not visible to me, may be network issue or something else
20:14:16 From Rehan Alı WAKKAS to Everyone:
	Import pandas as pd and import pandora as pa.
	What is pd and pa ?
20:14:28 From farhan to Everyone:
	Just names
20:15:06 From Ikhlas Bhojani to Everyone:
	koi question ho tw hand raise kriyea jese i moka milega me unmute krdonga
20:15:41 From Talha to Everyone:
	Replying to "Import pandas as pd ..."
	
	Alias, instead of writing long words pandas and pandora, we can write pd and pa as their short form
20:15:45 From Rehan Alı WAKKAS to Everyone:
	@Ikhlas Bhojani  
	Import pandas as pd and import pandora as pa.
	What is pd and pa ?
20:16:25 From Ikhlas Bhojani to Everyone:
	Replying to "@Ikhlas Bhojani  
	Im..."
	
	alias
20:16:43 From Jazil Hashmi to Everyone:
	Import pandas could not be resolved from source. Why is this error coming? @Ikhlas Bhojani
20:16:55 From Ikhlas Bhojani to Everyone:
	Replying to "@Ikhlas Bhojani  
	Im..."
	
	like nick name
20:17:36 From Ikhlas Bhojani to Everyone:
	!pip install pandas
20:17:46 From Rehan Alı WAKKAS to Everyone:
	Replying to "@Ikhlas Bhojani  
	Im..."
	
	Do they refer to Directories or what ?
20:19:58 From Abdullah to Everyone:
	Pandas is usually imported under the pd alias. alias: In Python alias are an alternate name for referring to the same thing. Create an alias with the as keyword while importing: import pandas as pd. Now the Pandas package can be referred to as pd instead of pandas .
20:20:30 From farhan to Everyone:
	These are nicknames used by community
20:25:02 From ahsan rasheed to Everyone:
	Mary kush lectures rah gy hain
20:25:15 From ahsan rasheed to Everyone:
	Kia ya lecture record ho rhy hain
20:25:23 From ABDUL KHALIQ to Everyone:
	g
20:25:26 From ABDUL KHALIQ to Everyone:
	youtube
20:25:31 From ABDUL KHALIQ to Everyone:
	panaverse dao
20:25:48 From ahsan rasheed to Everyone:
	Thanks
20:26:30 From Kamran Ahmed to Everyone:
	tabular form in panada
20:26:46 From Sarwar Faridi to Everyone:
	TABULAR
20:26:54 From Sarwar Faridi to Everyone:
	2D
20:26:57 From Kamran Ahmed to Everyone:
	index value also shown
20:27:06 From Ahmed Siddiqui to Everyone:
	matrix
20:27:07 From Kamal Hassan to Everyone:
	series men indexing h or tabular form mn h
20:29:56 From Kaleem to Everyone:
	sir series ma duplicate values bhi dy kar daikhain!!
20:35:09 From Zeeshan Abbas to Everyone:
	Sir what is INT64
20:37:19 From Ikhlas Bhojani to Everyone:
	koi question he tw hand raise krke rakhen
20:37:51 From Zeeshan Abbas to Everyone:
	mera question hai what is INT64
20:38:04 From Abdullah to Everyone:
	smj e ni aya 
	repeat krwa dyen
20:39:23 From Altaf Hussain to Everyone:
	Just like Chart of accounts in Accounting...
20:39:44 From Ahmed Siddiqui to Everyone:
	Reacted to "Just like Chart of a..." with 👍
20:40:40 From hi to Everyone:
	what is int 64
20:40:45 From hi to Everyone:
	dtype: int 64
20:40:54 From Zeeshan Abbas to Everyone:
	Sir why is showing INT64 in below
20:40:58 From Ikhlas Bhojani to Everyone:
	Replying to "mera question hai wh..."
	
	type hoti he data ki
20:42:24 From Kaleem to Everyone:
	in our structure data types of data we use key, value /key, pair values to define our data, how to translate that data Series?
20:42:27 From Asif Ali Shaikh to Everyone:
	int 64 is memory
20:42:44 From Asif Ali Shaikh to Everyone:
	Web3
20:45:11 From Zeeshan Abbas to Everyone:
	Reacted to "Web3" with 👍
20:46:15 From Galaxy to Everyone:
	Sir g account udaar dy dy
20:46:25 From Galaxy to Everyone:
	Reacted to Sir g account udaar ... with "😂"
20:46:40 From Ayesha Arshad to Everyone:
	Reacted to "Sir g account udaar ..." with 😂
20:46:40 From Ayesha Arshad to Everyone:
	Removed a 😂 reaction from "Sir g account udaar ..."
20:46:41 From jhon wick to Everyone:
	Reacted to "Sir g account udaar ..." with 😂
20:46:43 From Ayesha Arshad to Everyone:
	Reacted to "Sir g account udaar ..." with 😂
20:46:54 From Taif Ullah to Everyone:
	is bing equal to gpt 4
20:49:29 From fahad rasheed to Everyone:
	2 dimension data hy pora select krna parhyga "" mn
20:49:29 From Azfar Suhail to Everyone:
	from nptyping import DataFrame as DF, Structure as S
	
	s2 : DF[S["Abc : str"]] = pd.Series(['a','b','c','d','e'])
	s2
20:49:29 From Azfar Suhail to Everyone:
	this is working
20:51:57 From Saboor Hussain to Everyone:
	Reacted to "Sir g account udaa..." with 😂
20:51:59 From Saboor Hussain to Everyone:
	Removed a 😂 from "Sir g account udaa..."
20:58:40 From jhon wick to Everyone:
	yes
20:59:04 From farhan to Everyone:
	Kindly unmute
20:59:22 From Ikhlas Bhojani to Everyone:
	Replying to "Kindly unmute"
	
	wait
21:00:43 From PIAIC80919 Muhammad Asad to Everyone:
	Assalamu Aliakum
21:01:33 From Faizan Hassan to Everyone:
	s1.name kar k kar saktay hon ge
21:01:43 From PIAIC80919 Muhammad Asad to Everyone:
	I joined late on zoom meet so kindly share links that sir share until now
21:02:26 From Taif Ullah to Everyone:
	Replying to "I joined late on zoo..."
	
	every thing will be on github
21:04:19 From PIAIC80919 Muhammad Asad to Everyone:
	Numpy aur Pandas kay liya sir nay koi book share ki hai kay nahi
21:04:42 From Amanat Wattoo to Everyone:
	Replying to "Numpy aur Pandas kay..."
	
	no
21:05:21 From PIAIC80919 Muhammad Asad to Everyone:
	aur python kay liya koi alag WhatsApp group hai to please uska b link share kardien
21:06:00 From Amanat Wattoo to Everyone:
	Replying to "aur python kay liya ..."
	
	no koi group nhi bnia h
21:07:17 From Abdullah to Everyone:
	upper array wala code knsa ha??
21:07:51 From Hamza to Everyone:
	"Shape", "Shape"
21:08:10 From Hamza to Everyone:
	"Size", "Size"
21:08:26 From SheikhMAqib to Everyone:
	Double coat
21:08:33 From Azfar Suhail to Everyone:
	Shape turtle se import kara hai
21:08:51 From Azfar Suhail to Everyone:
	shape nptyping se import nhi howa
21:09:34 From Muhammad Uzair to Everyone:
	shape galat import ha
21:09:35 From Khadija Zahid to Everyone:
	shape ko kindly ek br explain kr den dbra
21:09:38 From PIAIC80919 Muhammad Asad to Qasim(CGAIO)(Direct Message):
	Assalamu Aliakum Sir Kindly sir mujhe bta dien k Data Science kay liya Math aur Statistic kay kon si books and courses hum karien
21:09:50 From Yasir to Everyone:
	shape import
21:09:53 From Yasir to Everyone:
	missing
21:09:56 From Muhammad Uzair to Everyone:
	from import typing shape
21:10:11 From Saboor Hussain to Everyone:
	sir
21:10:19 From Saboor Hussain to Everyone:
	aap nptyping se shape ko import karen
21:10:21 From Yasir to Everyone:
	import nhi kia shape
21:10:24 From farhan to Everyone:
	Shape import nahi thi
21:10:25 From Azfar Suhail to Everyone:
	turtle se import kara hai
21:14:10 From sadia to Everyone:
	can we get values 0 1 2 3 4 5 6 7 8 in vertical, abhi data horizontal arha hai
21:18:10 From Faiz M to Everyone:
	Sir chezy hard sy hard hoti ja rahe hy. aaj tho sir k oper oper ja raha hy.
21:18:56 From Qasim(CGAIO) to Everyone:
	https://www.w3schools.com/python/pandas/data.js
21:19:20 From Khadija Zahid to Everyone:
	html wala b ek br code dekha k bta de plz
21:19:22 From Abdullah to Everyone:
	kindly class k bd groups me sessions ka link send kr dia kryen
21:21:27 From Abdullah to Everyone:
	Replying to "kindly class k bd gr..."
	
	@Ikhlas Bhojani
21:22:11 From Ahmed Siddiqui to Everyone:
	what if data size in millions, what kind of preprocessing is required before handing over to pandas?
21:22:41 From Ikhlas Bhojani to Everyone:
	Replying to "kindly class k bd gr..."
	
	me ap logo ke group me nhi hn
21:22:59 From Abdullah to Everyone:
	Replying to "kindly class k bd gr..."
	
	bro sir sy kah dyen 
	ya sir Imran sy request kr dyen
21:24:13 From Ikhlas Bhojani to Everyone:
	Replying to "html wala b ek br co..."
	
	pd.read_html("url")
21:26:02 From Kaleem to Everyone:
	how to make identical data ?
21:26:19 From Afifa Dar to Everyone:
	colmn3 k chexk me ==2 se kya horaha ?
21:29:40 From PIAIC80919 Muhammad Asad to Qasim(CGAIO)(Direct Message):
	sir assignment b day dein practice kay liya
21:32:29 From Ali Zar FSD to Everyone:
	sliding
21:32:41 From Ali Zar FSD to Everyone:
	likha gya sir
21:33:00 From fahad rasheed to Everyone:
	sir thora data large kryn plx
21:33:18 From fahad rasheed to Everyone:
	for slicing thora data bardhae
21:39:55 From raheela to Everyone:
	Name is tort ???
21:40:46 From Naveed Delattre to Everyone:
	it’s toad
21:41:45 From Altaf Hussain to Everyone:
	PIAIC-173738
21:41:51 From Hamza to Everyone:
	PIAIC-201785
21:41:52 From jhon wick to Everyone:
	piaic 223880
21:41:54 From Hina Zargham to Everyone:
	PIAIC101499
21:41:54 From Hatif Humayun to Everyone:
	PIAIC-52822
21:41:54 From Ahmed Siddiqui to Everyone:
	PIAIC123456
21:41:56 From Arif Najmi to Everyone:
	125657
21:42:00 From Rehan Baig - PIAIC73919 to Everyone:
	PIAIC73919
21:42:00 From STONE to Everyone:
	ZAM - 786
21:42:01 From M. Waheed Iqbal (PIAIC_126369) to Everyone:
	PIAIC_126369
21:42:03 From . to Everyone:
	PIAIC210905
21:42:06 From ABDUL KHALIQ to Everyone:
	PIAIC-604031
21:42:11 From Arshad Siddiqui to Everyone:
	PIAIC120702
21:42:13 From Ali Zar FSD to Everyone:
	PIaic 223972
21:42:13 From Azfar Suhail to Everyone:
	PIAIC218333
21:42:14 From Kamran Ahmed to Everyone:
	PIAIC139495
21:42:18 From Ahmed to Everyone:
	216511
21:42:20 From Ayesha Arshad to Everyone:
	PIAIC-225620
21:42:25 From Kamal Hassan to Everyone:
	PIAIC58320
21:42:29 From Ahmed to Everyone:
	PIAIC-2165111
21:42:30 From Kaleem to Everyone:
	PIAIC:001100
21:42:34 From Arif Najmi to Everyone:
	PIAIC 125657
21:42:35 From Yasir to Everyone:
	PIAIC63502
21:42:37 From Ahmed to Everyone:
	PIAIC-216511
21:42:41 From Ali to Everyone:
	PIAIC76588
21:42:46 From M Qasim to Everyone:
	PIAIC178397
21:42:55 From Dr. Ghulam Shabbir to Everyone:
	PIAIC208889
21:42:59 From IMRAN to Everyone:
	PIAIC216423
21:43:04 From PIAIC80919 Muhammad Asad to Qasim(CGAIO)(Direct Message):
	PIAIC80919
21:43:04 From Ahmed to Everyone:
	PIAIC-216511
21:43:16 From Kamal Hassan to Everyone:
	PIAIC,58321
21:43:29 From Zeeshan Abbas to Everyone:
	PIAIC221479
21:43:43 From Amanat Wattoo to Everyone:
	PIAIC174651
21:44:12 From Ahsan to Everyone:
	PIAIC185091
21:44:26 From Amanat Wattoo to Everyone:
	@Ikhlas Bhojani bhai chat ko save kaisy save krwia h
21:45:09 From Ikhlas Bhojani to Everyone:
	Replying to "@Ikhlas Bhojani bhai..."
	
	neeche three dot se
21:46:20 From Ikhlas Bhojani to Everyone:
	Replying to "@Ikhlas Bhojani bhai..."
	
	Jahan msg likhte hen uske neeche three dot he
21:46:30 From Amanat Wattoo to Everyone:
	Replying to "@Ikhlas Bhojani bhai..."
	
	ok find thanks
21:47:27 From Amanat Wattoo to Everyone:
	Replying to "@Ikhlas Bhojani bhai..."
	
	found


"""

import re 

patterns : str = r'''
(\d{2}:\d{2}:\d{2}) From (.*) to Everyone:
	(PIAIC-? ?\d{5,6})
'''

data : list[list[str]] = re.findall(patterns, x)

data

[('21:41:45', 'Altaf Hussain', 'PIAIC-173738'),
 ('21:41:54', 'Hina Zargham', 'PIAIC101499'),
 ('21:41:54', 'Ahmed Siddiqui', 'PIAIC123456'),
 ('21:42:00', 'Rehan Baig - PIAIC73919', 'PIAIC73919'),
 ('21:42:03', '.', 'PIAIC210905'),
 ('21:42:11', 'Arshad Siddiqui', 'PIAIC120702'),
 ('21:42:13', 'Azfar Suhail', 'PIAIC218333'),
 ('21:42:20', 'Ayesha Arshad', 'PIAIC-225620'),
 ('21:42:34', 'Arif Najmi', 'PIAIC 125657'),
 ('21:42:37', 'Ahmed', 'PIAIC-216511'),
 ('21:42:46', 'M Qasim', 'PIAIC178397'),
 ('21:42:59', 'IMRAN', 'PIAIC216423'),
 ('21:43:04', 'Ahmed', 'PIAIC-216511'),
 ('21:43:29', 'Zeeshan Abbas', 'PIAIC221479'),
 ('21:44:12', 'Ahsan', 'PIAIC185091')]

In [47]:
df : pd.DataFrame = pd.DataFrame(data, columns=['Time', 'Name',"Roll Number"])

df

Time                     Name   Roll Number
0   21:41:45            Altaf Hussain  PIAIC-173738
1   21:41:54             Hina Zargham   PIAIC101499
2   21:41:54           Ahmed Siddiqui   PIAIC123456
3   21:42:00  Rehan Baig - PIAIC73919    PIAIC73919
4   21:42:03                        .   PIAIC210905
5   21:42:11          Arshad Siddiqui   PIAIC120702
6   21:42:13             Azfar Suhail   PIAIC218333
7   21:42:20            Ayesha Arshad  PIAIC-225620
8   21:42:34               Arif Najmi  PIAIC 125657
9   21:42:37                    Ahmed  PIAIC-216511
10  21:42:46                  M Qasim   PIAIC178397
11  21:42:59                    IMRAN   PIAIC216423
12  21:43:04                    Ahmed  PIAIC-216511
13  21:43:29            Zeeshan Abbas   PIAIC221479
14  21:44:12                    Ahsan   PIAIC185091