# Numpy
Numerical Python (NumPy) is a popular Python library used for numerical computations and handling arrays or matrices.
It provides support for multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

#### Why do we use NumPy?

* `Efficient Array Operations`: NumPy allows for fast operations on arrays/matrix computations, making it essential for scientific and numerical calculations.
* `Data Representation`: It provides a convenient and efficient way of representing and manipulating numerical data.
* `Integration with Other Libraries`: It integrates well with other Python libraries and tools used in data analysis, machine learning, and scientific computing.

#### Advantages of NumPy:

* `Performance`: It's highly optimized and written in C, making operations significantly faster than standard Python lists for numerical computations.
* `Broadcasting`: Allows operations on arrays of different shapes, which makes code concise and easier to read.
* `Array-Oriented Computing`: Provides a wide range of mathematical functions for fast operations on entire arrays without the need for writing loops.
* `Memory Efficiency`: NumPy arrays use less memory compared to Python lists for storing data.
* `Broad Usage`: Widely used in fields like data science, machine learning, scientific research, and engineering due to its speed and functionality.


#### Scalar Values
Doesnt have any dimesion

In [2]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

print(a) # prints
print(a.shape) # prints the shape of the object () = 0 -Denormalized
print(a.dtype) # prints the dtype of the object
print(a.ndim) # prints the number of dimensions - Scalar values have 0 dimension
print(a.size) # prints the size of the object
print(a.itemsize) # prints the itemsize of the object


1000
()
int32
0
1
4


#### Vector Type

In [8]:

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

a.size?

' object [1 2 3 4]'

'objec shape (4,)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in Array : 4'

'4'

Type:        int
String form: 4
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

#### Matrix

In [9]:
data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object

' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'objec shape (3, 4)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in Array : 12'

'4'

### Numpy with NDArray typing support

In [3]:
%%time 
from nptyping import NDArray, Shape, UInt32
from typing import Any

data : NDArray[Shape["10"],Any] = np.arange(1,20);

d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
#d1 + 5 #will give error because doesnt work on list

print(data);
print(data + 5)
print(data ** 2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361]
CPU times: total: 0 ns
Wall time: 28 ms


In [11]:
print("List Method\n")
data1 : list[int] = list(range(1,21))
print(data1)
print(data1[5:11])
#data1[5:11] = 1000 #list doesnt allow this operation
print(data1)

print("\nNumpy Mehtod \n")
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)


List Method

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Numpy Mehtod 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


In [4]:
from typing import Any
from nptyping import NDArray, Shape, Bool


state_bank : NDArray[Shape["10"], Any] = np.array([1, 7, 8, 10])
select : NDArray[Shape["10"], Bool] = np.array([True, False, False, True])

ubl_bank : NDArray[Shape["100"], Any] = np.random.randint(1, 100, 20);

display(state_bank)
display(state_bank[select])

display(ubl_bank)
display(ubl_bank[ubl_bank % 2 == 0])

array([ 1,  7,  8, 10])

array([ 1, 10])

array([ 3, 65,  8, 52, 36, 49, 36, 13, 80, 97, 78, 79, 32, 57,  7, 92, 59,
       59, 74, 59])

array([ 8, 52, 36, 36, 80, 78, 32, 92, 74])

In [21]:
x : NDArray[Shape["5"], Any] = np.array([1, 3, 4, 5, 7])
y : NDArray[Shape["5"], Any] = np.array([6, 3, 2, 5, 100])

display(x)
np.where(x > y, x, y)


array([1, 3, 4, 5, 7])

array([  6,   3,   4,   5, 100])

In [23]:
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                [4, 5, 6]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                [4, 5]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                ["B"]])


[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


#### Create any dimension array

In [15]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(f"1D Array: {a}")

a : NDArray[Shape["Size, Size"],Any] = np.arange(3*3).reshape(3,3)
print(f"\n2D Array \n{a}")

a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(f"\n3D Array \n{a}")

1D Array: [1 2 3 4]

2D Array 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3D Array 
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [16]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])